apiVersion: apps/v1
kind: Deployment
metadata:
  name: react
  labels:
    type: create-react-app
    language: js
spec:
  replicas: 3
  selector:
    matchLabels:
      type: create-react-app
  template:
    metadata:
      labels:
        type: create-react-app
        language: js
    spec:
      containers:
      - name: frontend
        image: "redaloukil/frontend"
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          periodSeconds: 1
        livenessProbe:
          httpGet:
            path: /
            port: 3000
