apiVersion: app-v1
kind: Deployment
metadata:
  name: react
  labels:
    type: create-react-app
    language: js
spec:
  replicas: 1
  selector:
    matchLabels:
      type: create-react-app
  template:
    metadata:
      labels:
        type: create-react-app
        language: js
    spec:
      containers:
      - name: frontend
        image: "redaloukil/frontend:latest"
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          periodSeconds: 1
        livenessProbe:
          httpGet:
            path: /
            port: 3000
---

apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30007
  selector:
    type: vue-app